name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: tenderlove/setup-ruby@cebe8d96a9e3ab26f5130cfe81e4d95c4d9c0e8a
        with:
          ruby-version: "3.0.2"
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test
